name: Test
on:
  push:
    branches: 
      - "main"    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --prefix server
      - run: npm run build --prefix server
      - run: npm install --prefix generator
      - run: npm run build --prefix generator
      - run: npm run test --prefix generator
